meriyah/meriyah

- README.md
- src/errors.ts
- src/lexer/scan.ts
- src/parser.ts
- src/token.ts
- test/parser/next/nullCoalescing.ts
This implements support for the latest Stage 3 features.
> WIP! Implements nullish coalescing and optional chaining (stage 3)

- src/lexer/comments.ts
- src/lexer/common.ts
- src/lexer/index.ts
- src/lexer/scan.ts
- src/parser.ts
> Revert "Fix tracking of parser location regardless of line-ending format"

- src/lexer/comments.ts
- src/lexer/common.ts
- src/lexer/scan.ts
- test/parser/miscellaneous/comments.ts
- test/parser/miscellaneous/loc.ts
- test/parser/miscellaneous/onComment.ts
- test/parser/miscellaneous/onToken.ts
Should fix https://github.com/meriyah/meriyah/issues/46, added a test to make sure it doesn't break in the future.
In addition fixed a bug causing onComment to never be called.
> Fix line ending handling and onComment

- src/lexer/scan.ts
- test/parser/miscellaneous/onComment.ts
HTML comments include parts of their prefix
> Fix html comments

- src/common.ts
- src/parser.ts
this will fix the issue https://github.com/meriyah/meriyah/issues/60
> Create unique key and value for Object pattern

- src/lexer/scan.ts
- test/parser/miscellaneous/onToken.ts
> fix(scan): token start should skip leading white spaces and comments

- src/common.ts
- src/estree.ts
- src/parser.ts
- test/parser/next/optional-chaining.ts
A draft attempt for https://github.com/estree/estree/blob/master/es2020.md#chainexpression
> feat(parser): wip support latest ESTree spec on optional chaining

- src/lexer/jsx.ts
- src/parser.ts
- test/parser/miscellaneous/jsx.ts
> fix(lexer): fix missed new line char in jsx parser

- src/estree.ts
- src/parser.ts
- test/parser/expressions/bigint.ts
> fix(estree): fix the estree interface for BigIntLiteral, cleanup RegExpLiteral

- src/parser.ts
- test/parser/next/optional-chaining.ts
closes #98
-----
This gets the job done, but I really don't like this hack.
> fix: fix wrong ChainExpression wrapper

- src/estree.ts
- src/parser.ts
- test/parser/expressions/in.ts
- test/parser/miscellaneous/directives.ts
- test/parser/module/export.ts
closes #97, #99
-----
Prettier touches few lines of code.
> fix(parser): follow latest estree spec on ExportAllDeclaration

- src/parser.ts
- test/parser/statements/for-in.ts
> fix: ForInOfLoopInitializer only applies in strict mode

- README.md
- src/common.ts
- src/lexer/comments.ts
- src/lexer/scan.ts
- src/parser.ts
- test/parser/miscellaneous/onComment.ts
- test/parser/miscellaneous/onToken.ts
Also fixed onToken, the "start/end" should respect ranges flag, not loc flag.
closes #95
> feat: support loc flag for onComment and onToken

- src/parser.ts
- test/parser/next/decorators.ts
> refactor: simplify InvalidLeadingDecorator check

- src/parser.ts
- src/token.ts
- test/parser/expressions/class.ts
- test/parser/expressions/object.ts
> fix: bigint is a number literal

- src/lexer/jsx.ts
- src/parser.ts
- test/parser/miscellaneous/jsx.ts
These are minor missing code from existing jsx implementation.
> few fixes for jsx

- src/parser.ts
- test/parser/next/decorators.ts
> fix: fix range of ExportDeclaration/ClassDeclaration/ClassExpression after decorators

- src/parser.ts
- src/token.ts
- test/parser/next/public-fields.ts
> fix: fix infinite loop on broken class body

- src/lexer/string.ts
- test/lexer/strings.ts
- test/test262-parser-tests/parser-tests.ts
closes #146
-----
Also cleaned up test262 tests.
> fix(lexer): fix line continuation with \r\n

- package.json
- scripts/bundle.js
Closes https://github.com/meriyah/meriyah/issues/141
> Fix CommonJS entry point in package.json

- src/parser.ts
- test/parser/declarations/functions.ts
> fix(parser): fix missing rejection on function name

- src/parser.ts
- test/parser/expressions/exponentiation.ts
> fix(parser): rejects "await 2**2"

- src/parser.ts
- test/parser/statements/return.ts
> fix(parser): fix wrong starting loc for any non-trival expression in return statement

- src/parser.ts
- test/parser/miscellaneous/jsx.ts
> fix(parser): allow regular expression in JSXExpressionContainer

- src/parser.ts
- test/parser/next/private_methods.ts
Also fixed the error message for invalid super call.
closes #203
> fix(parser): super call should be allowed in private method

- .github/workflows/node.js.yml
- src/parser.ts
- test/parser/miscellaneous/regex.ts
- test/parser/statements/for-await-of.ts
> fix(parser): support top level for-await in module context

- src/lexer/identifier.ts
- test/parser/statements/for-of.ts
> fix(parser): ~ (0x7e) is a valid stop for Identifier or Keyword

- src/parser.ts
- test/parser/module/import.ts
> fix(parser): reject "import from 'foo'"

- src/parser.ts
Based on the discussion in #270
> chore: remove unreachable code

- README.md
- src/parser.ts
- test/parser/next/hashbang.ts
Hashbang is a finished proposal. https://github.com/tc39/proposals/blob/main/finished-proposals.md
BREAKING CHANGE: hashbang now works without "next" option.
> feat(parser): move hashbang out of "next" option

- src/estree.ts
- src/parser.ts
- test/parser/module/export.ts
- test/parser/next/import-attributes.ts
> fix(parser): add missing import-attributes support in ExportNamedDeclaration

- src/errors.ts
- src/estree.ts
- src/lexer/common.ts
- src/parser.ts
- test/parser/module/export.ts
- test/parser/module/import.ts
- test/parser/next/import-attributes.ts
- test/test262-parser-tests/unsupported-features.txt
> feat(parser): support arbitrary module namespace names

- src/common.ts
- src/lexer/jsx.ts
- src/lexer/scan.ts
- src/lexer/template.ts
- src/parser.ts
- test/parser/miscellaneous/onToken.ts
template and jsx scan are special, there are two cases of re-scan current token, add a param replaceLast=false to setToken to cover the two cases.
closes #215, closes #216
> fix(parser): fix onToken callback for template and jsx

- src/common.ts
- src/lexer/comments.ts
- src/lexer/identifier.ts
- src/lexer/jsx.ts
- src/lexer/numeric.ts
- src/lexer/regexp.ts
- src/lexer/scan.ts
- src/parser.ts
- test/parser/miscellaneous/jsx.ts
- test/parser/miscellaneous/onToken.ts
> fix(parser): fix jsx with comments in tag

- .github/workflows/update-test262.yml
Tested on my fork
- CI job https://github.com/fisker/meriyah/actions/runs/11432047006/job/31801894284
- Created PR https://github.com/fisker/meriyah/pull/6/files
> ci: add automated job to update test262

- src/lexer/jsx.ts
- src/parser.ts
- test/parser/miscellaneous/jsx.ts
> fix(parser): fix JSX attribute name parse

- src/meriyah.ts
- src/parser.ts
- src/token.ts
- test/parser/expressions/await.ts
> fix(parser): get/set/from/of are allowed as identifiers

- package.json
[`module-sync`](https://nodejs.org/api/packages.html#conditional-exports)
> feat: add `module-sync` condition

- .prettierignore
- eslint.config.mjs
- package.json
- scripts/bundle.mjs
> chore: clean benchmark related code

- .github/workflows/node.js.yml
- test/production/production-tests.ts
- vitest.config.ts
Prevent breaking bundle script
> test: add production test

- .github/workflows/node.js.yml
- package.json
- scripts/bundle.mjs
- test/production/production-tests.ts
- vitest.config.ts
Fixes #391
~Wait for answer to https://github.com/meriyah/meriyah/issues/391#issuecomment-2798756608~
130 KB -> 68.4 KB
> build: move type files to `dist/types`, remove `.d.ts.map` files from published package

- src/estree.ts
- src/parser.ts
- test/parser/declarations/async-function.ts
- test/parser/miscellaneous/jsx.ts
- test/parser/module/export.ts
- test/parser/module/import.ts
> fix(parser): `attributes` on `{ExportAll,ExportNamed,Import}Declaration` is now always an array

- src/parser.ts
- test/parser/expressions/parenthesized-expression.ts
> fix: preserve nested `ParenthesizedExpression`

- src/common.ts
- src/errors.ts
- src/lexer/comments.ts
- src/lexer/common.ts
- src/lexer/identifier.ts
- src/lexer/jsx.ts
- src/lexer/numeric.ts
- src/lexer/regexp.ts
- src/lexer/scan.ts
- src/lexer/string.ts
- src/lexer/template.ts
- src/parser.ts
- test/lexer/comments.ts
- test/lexer/identifiers.ts
- test/lexer/line-terminators.ts
- test/lexer/numbers.ts
- test/lexer/privatename.ts
- test/lexer/punctuators.ts
- test/lexer/regexp.ts
- test/lexer/scanSingleToken.ts
- test/lexer/skiphashbang.ts
- test/lexer/strings.ts
- test/lexer/template.ts
- test/lexer/unicode-escape.ts
- test/lexer/whitespace.ts
Should we call it `State` or `Parser`?
> refactor: covert parser state to class

- test/parser/statements/return.ts
> test: add tests for CommonJS context

- src/parser.ts
- test/parser/miscellaneous/__snapshots__/ranges.ts.snap
- test/parser/miscellaneous/ranges.ts
> fix(parser): fix `MemeberExpression` location inside `For{,Of,In}Statement`

- src/parser.ts
- test/parser/expressions/__snapshots__/super.ts.snap
- test/parser/miscellaneous/__snapshots__/public-fields.ts.snap
- test/parser/miscellaneous/public-fields.ts
Part of #416
I only fix the one without a decorator.
> fix(parser): fix location of static class property

- src/parser.ts
- src/parser/parser.ts
> refactor: reuse `finishNode` in `parseSource`

- src/lexer/identifier.ts
- test/parser/declarations/__snapshots__/async-function.ts.snap
- test/parser/declarations/__snapshots__/async-generator.ts.snap
- test/parser/declarations/__snapshots__/functions.ts.snap
- test/parser/expressions/__snapshots__/arrow.ts.snap
- test/parser/expressions/__snapshots__/async-arrow.ts.snap
- test/parser/expressions/__snapshots__/async-function.ts.snap
- test/parser/expressions/__snapshots__/class.ts.snap
- test/parser/expressions/__snapshots__/function.ts.snap
- test/parser/expressions/__snapshots__/identifier.ts.snap
- test/parser/expressions/__snapshots__/object.ts.snap
- test/parser/expressions/identifier.ts
- test/parser/miscellaneous/__snapshots__/directives.ts.snap
- test/parser/miscellaneous/__snapshots__/escaped-keyword.ts.snap
- test/parser/miscellaneous/__snapshots__/private_methods.ts.snap
- test/parser/next/__snapshots__/hashbang.ts.snap
- test/parser/next/__snapshots__/import-meta.ts.snap
- test/parser/statements/__snapshots__/labeled.ts.snap
> fix(parser): fix column of escaped identifier

- src/parser.ts
- test/parser/expressions/__snapshots__/class.ts.snap
- test/parser/expressions/class.ts
```
class C {static accessor = 42;}
^^^^^^^^^^^^^^ wrong
^^^^^^^^^^^^^^^^^^^^^ correct
```
> fix(parser): fix range of static class property named `accessor`, `get`, `set`, and `async`

- src/lexer/string.ts
- test/parser/expressions/__snapshots__/string.ts.snap
- test/parser/expressions/string.ts
Fixes https://github.com/meriyah/meriyah/issues/472
> fix(parser): fix line/column where string literal contains U+2028 or U+2029

- src/parser.ts
- test/parser/module/__snapshots__/import-attributes.ts.snap
- test/parser/module/import-attributes.ts
- test262/whitelist.txt
Ref https://github.com/meriyah/meriyah/issues/481#issuecomment-3000124591
> fix(parser): stop complaining about named import/export with `{type: "json"}` attribute

- src/parser.ts
- test/parser/next/__snapshots__/decorators.ts.snap
https://github.com/meriyah/meriyah/issues/420#issuecomment-3027552486
> fix(parser): fix location of `Decorator.expression`

- .github/workflows/node.js.yml
- README.md
- package.json
- scripts/shared.d.mts
- scripts/shared.mjs
- test/lexer/regexp.ts
- test262/shared.mjs
Ref: https://github.com/meriyah/meriyah/issues/510
> feat!: require Node.js v20

- README.md
- scripts/internal-eslint-plugin/prefer-parse-source-options.mjs
- src/options.ts
- src/parser.ts
- test/parser/miscellaneous/api.ts
- test/parser/statements/return.ts
> feat!: add `sourceType: 'commonjs'`, deprecate `globalReturn` option
