meriyah/meriyah

src/lexer/comments.ts, src/lexer/common.ts, src/lexer/index.ts, src/lexer/scan.ts, src/parser.ts
Abstract the handling of a line break to be agnostic of whether the sequence is any of CR,CRLF, LF, or LFCR.
=> Fix tracking of parser location regardless of line-ending format

README.md, package-lock.json, src/common.ts, src/lexer/common.ts, src/lexer/index.ts, src/lexer/scan.ts, src/parser.ts, test/parser/miscellaneous/onComment.ts, test/parser/miscellaneous/onToken.ts, tsconfig.json
Add onToken callback function based on the same feature in [Cherow](https://github.com/cherow/cherow). This will allow comment attachment using tools like [estraverse](https://github.com/estools/estraverse), like Acorn and Esprima do.
=> Add onToken - based on Cherow

src/parser.ts
The "id" property should come before "init". This is useful for Estree iterators that don't preset traversal order of Node keys.
=> Fix order of VariableDeclarator properties

src/parser.ts
I checked how both Acorn orders node keys and how Estraverse walks the tree.
The following nodes have been adjusted to make dynamic tree iterators act similarly:
1. ArrowFunctionExpression
2. ExportNamedDeclaration
3. ForStatement
4. ForOfStatement
5. FunctionDeclaration
6. FunctionExpression
=> Change key order of other nodes

src/estree.ts, src/parser.ts, test/parser/miscellaneous/api.ts, test/parser/next/nullCoalescing.ts
The Estree spec extends the LogicalExpression node type by adding
the '??' operator value to it:
https://github.com/estree/estree/blob/master/es2020.md#logicalexpression
=> fix: rename CoalesceExpression

src/estree.ts, src/parser.ts, test/parser/expressions/object.ts, test/parser/expressions/template.ts
closes #109, #108
-----
The range/loc in TemplateElement was wrong, because we need to move parser to nextToken before finalise it.
This PR doesn't address null "cooked" value, as indicated in estree spec. I merely added the typing into our estree types.
=> fix: fix wrong cooked value in TemplateElement, fix wrong loc and range in various template nodes

src/common.ts, src/errors.ts, src/parser.ts, test/parser/next/decorators.ts
closes #105
-----
Move to new decorator proposal broke the old code `@dec export class A {}`. Need to improve parseExportDeclaration to support decorator before export keyword.
=> fix: follow latest decorator proposal

src/lexer/string.ts, test/lexer/strings.ts, test/parser/miscellaneous/failure.ts, test/parser/miscellaneous/literals.ts, test/test262-parser-tests/parser-tests.ts
=> fix(lexer): \8 \9 are acceptable in web compatibility mode

src/token.ts, test/parser/expressions/logical.ts
Fixes invalid precedence of `<=` and `>=` operators
According to [mdn](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Operator_Precedence#table) `<=` and `>=` operators have precedence same as `<` and `>` and greater than equal operators.
At the moment expression `a >= b !== c >= d` parsed as `((a >= b) !== c) >= d`, but expected `(a >= b) !== (c >= d)`.
=> fix(parser): precedence of `<=` and `>=` operators

src/lexer/regexp.ts, test/lexer/regexp.ts
=> fix(lexer): fix wrong error when using regex flag s together with m or y

src/parser.ts, test/parser/expressions/await.ts, test/parser/expressions/optional-chaining.ts, test/parser/miscellaneous/escaped-keyword.ts
Such as foo[await 1], foo(await 1).
closes #212
=> fix(parser): allow top level await in expressions

src/lexer/regexp.ts, test/lexer/regexp.ts
=> feat(lexer): support new RegExp Indices flag "d"

src/lexer/regexp.ts
=> fix: use null as regex value in environment missing flag "d" support

src/estree.ts, src/parser.ts, test/parser/next/static-block.ts, test/parser/statements/static-block.ts
Attempts to fix #194 and one point from #214.
extend interface ClassBody {
body: [ MethodDefinition | PropertyDefinition | StaticBlock ];
}
interface StaticBlock <: BlockStatement {
type: "StaticBlock";
}
Proposal: https://github.com/tc39/proposal-class-static-block
MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/Class_static_initialization_blocks
V8 examples: https://v8.dev/features/class-static-initializer-blocks
ESTree: https://github.com/estree/estree/blob/master/es2022.md#staticblock
=> feat(parser): Add support for class static initialization block

src/lexer/identifier.ts, src/token.ts, test/lexer/identifiers.ts, test/parser/miscellaneous/escaped-keyword.ts
fix: async is not reserved word, and some fix on reserved words
fix: dot property should allow escaped keyword in strict mode
closes #221, #224
=> Fix escaped async keyword and escaped dot property

src/parser.ts, test/parser/expressions/class.ts
closes #231
Not 100% sure about the implementation.
The spec didn't tell me exact steps. https://262.ecma-international.org/13.0/#sec-static-semantics-isstatic
I tried to use an allowed-list (~~whitelist~~), but there are few conditions like `static "str-id" = 1;` `static *generator()`, I am not confident to cover them all.
So I extended the current blocked-list (~~blacklist~~) for the logic.
=> fix(parser): "static" can be used as an identifier in ClassElement

src/parser.ts, test/parser/expressions/import_call.ts
The PR fixes an error with the following construct:
```js
function() {
import('some.js').then(e => e || {}), (this.some = !0);
}
```
=> Fix issue with import located in a sequence

package.json
Fix for the following problem:
```
Could not find a declaration file for module 'meriyah'. '/path/to/node_modules/meriyah/dist/meriyah.esm.mjs' implicitly has an 'any' type.
There are types at '/path/to/node_modules/meriyah/dist/src/meriyah.d.ts', but this result could not be resolved when respecting package.json "exports". The 'meriyah' library may need to update its package.json or typings.
import { parseScript } from 'meriyah';
```
=> Ensure that types are exported

src/parser.ts, test/parser/expressions/class.ts
Fixes the issue described below by remembering the HasConstructor flag and restoring it after parsing the class body.
---
Meriyah fails to parse the following code:
```
new class {
start() {
new class {
constructor() {}
}
}
constructor() {}          
}
```
Seems that the position of the outer constructor is what causes the problem cause when the outer constructor is above the start method Meriyah can parse it.
This snippet succeeds
```
new class {
constructor() {}          
start() {
new class {
constructor() {}
}
}
}
```
=> Fix parsing of nested class with constructor

src/parser.ts, test/parser/next/public-fields.ts
Double assignment is not parsed correctly in class' property definition.
`class A { b = c = d; }` is parsed like `class A { b = c; = d; }` which is not a valid AST.
This PR fixes it along with other possible assignment operators.
=> Fix assignment as a value for property definition

src/parser.ts, test/parser/statements/do-while.ts
Fix for bug found when attempting to parse a regexp test immediately after a do-while loop terminated by a semicolon.
=> fix for regexp test after do-while with semicolon

README.md, src/common.ts, src/parser.ts, test/parser/miscellaneous/onInsertedSemicolon.ts
Adds support for the `onInsertedSemicolon` callback option, matching the base behavior of the `acorn` option of the same name. This option is used by `webpack` to identify when replacing the text of a node with a parenthesized expression would run afoul of a difference in runtime behavior if automatic semicolon insertion occurred.
Motivating example:
```js
console.log('hi!') // ASI occurs here
foo() // ASI occurs here
console.log(foo.name)
```
If webpack replaces `foo` with the imported expression `(0,some_module.foo)`, the resulting code has the runtime behavior of
```js
console.log('hi!')(0,some_module.foo)() // tried to call the result of `console.log`, TypeError
console.log((0,some_module.foo).name) // Correct code
```
On the other hand, if webpack tries to always insert a semicolon, …
=> feat(parser): add onInsertedSemicolon option

src/parser.ts, test/parser/declarations/functions.ts, test/parser/miscellaneous/pass.ts, test/parser/next/import-meta.ts
Fixes usage of `async` and `import` in comma expressions, like:
```js
async = 1, b = 2;
b = 2, async = 1;
import.meta, 1;
```
=> Fix usage of `async` and `import` in comma expression

src/parser.ts, test/parser/expressions/template.ts
The PR fixes these two corner cases with template strings:
```js
1. tag()`template string with octal or hex value`
2. String.raw`template string with octal or hex value`
```
=> Fix template strings with octal or hex values

src/parser.ts, test/parser/expressions/super.ts, test/parser/next/public-fields.ts
The PR fixes issues described in this issue: https://github.com/meriyah/meriyah/issues/257
=> Allow `super` to be used in arrow functions and in static object initialisation

README.md, src/common.ts, src/parser.ts, test/parser/miscellaneous/api.ts
Although it removes an option, this is not a breaking change as the option has no effect at all.
=> chore: remove specDeviation option which has never been passed to matchOrInsertSemicolon

README.md, src/common.ts, src/parser.ts, test/parser/miscellaneous/api.ts
This option added a "pattern" flag to Identifer node, but this feature was rejected by ESTree, https://github.com/estree/estree/issues/196 KFlash prematurelly added this when reading it.
Since it's not in ESTree spec, nobody would never relied on it. In this sense, not a breaking change.
=> chore: remove option identifierPattern

src/common.ts, src/parser.ts
I don't really understand what is that for, but found it's always `1`, and rollup is able to remove it during #264.
=> Remove unused `isArrow` from `classifyIdentifier`

src/parser.ts, test/parser/module/import.ts
There is an existing method does report better error.
```js
export function consume(parser: ParserState, context: Context, t: Token): void {
if (parser.token !== t) report(parser, Errors.ExpectedToken, KeywordDescTable[t & Token.Type]);
nextToken(parser, context);
}
```
=> chore: show proper error "Expected 'from'"

.gitignore, src/common.ts, src/parser.ts
This removes the coupling with the Context and PropertyKind enum definition.
The old code means we cannot modify Context and PropertyKind definition freely.
Related to #274
=> chore: remove explicit binary mask

src/parser.ts, test/parser/expressions/super.ts, test/parser/next/decorators.ts, test/parser/next/private_methods.ts, test/parser/next/public-fields.ts
A property definition needs to end with semicolon, newline, or implicit semicolon.
`class A { a b }` is invalid, needs `class A { a; b }` or `"class A { a\nb}"`.
closes #233
=> fix(parser): class property definition needs to be separated

.github/workflows/node.js.yml, README.md, package.json, scripts/bundle.js
BREAKING CHANGE: only distribute following files:
dist/meriyah.cjs
dist/meriyah.mjs
dist/meriyah.min.mjs
dist/meriyah.umd.js
dist/meriyah.umd.min.js
All transpiled with target: "ES2021"
=> chore: reduce dist files to esm, cjs, and umd

scripts/run-test262.ts, src/common.ts, test/test262-parser-tests/whitelist.txt
ECMA B.3.4 syntax error if catch param occurs in var declared names of catch block, unless catch param is binding identifier
=> fix(parser): fix annexB behaviour (webcompat) of catch param

package.json, scripts/run-test262.ts, src/lexer/regexp.ts, test/lexer/regexp.ts, test/test262-parser-tests/unsupported-features.txt
Note meriyah uses JavaScrip runtime to validate regexp pattern, so the v flag only works in JS runtime that supports it. For nodejs, it's v20.0.0+.
=> feat(lexer): support regexp v flag (unicodeSets)

src/common.ts, src/lexer/jsx.ts, src/lexer/scan.ts, src/parser.ts, src/token.ts, test/parser/miscellaneous/onToken.ts
closes #185
This is better I think. Previous fix will take "< /* xx */ /" as one token, that doesn't make sense, now it's "<" and "/" two tokens.
=> fix(parser): fix jsx parsing on '< / >'

src/common.ts, src/errors.ts, src/lexer/identifier.ts, src/lexer/numeric.ts, src/parser.ts
Meriyah actually reported the end position in ParseError, this change added tokenIndex/tokenLine/tokenColumn to ParseError as the start position, together with end position in index/line/column. User can catch the error from meriyah and then uses tool like @babel/code-frame to visualise the failing token.
closes #156
=> feat(parser): add token start and end index/line/column to ParseError

src/token.ts, test/parser/expressions/await.ts
=> fix(parser): all identifiers can be start of an expression

src/parser.ts, test/parser/expressions/template.ts
The parser fails to parse an octal string template when the tagged function contains arguments, for example:
```js
tag('a')`'\\00a0'`
```
=> Fix another issue with octal template strings

.github/workflows/node.js.yml
`npm i` is so [slow](https://github.com/meriyah/meriyah/actions/runs/14377174160/job/40312236071?pr=380#step:4:19), choose yarn since it can use directly on ci.
=> ci: use yarn to install dependencies

scripts/bundle.mjs
Before:
```console
$ node scripts/bundle.mjs
writing E:\oss\forks\meriyah\dist\meriyah.cjs
writing E:\oss\forks\meriyah\dist\meriyah.min.mjs
writing E:\oss\forks\meriyah\dist\meriyah.mjs
writing E:\oss\forks\meriyah\dist\meriyah.umd.min.js
writing E:\oss\forks\meriyah\dist\meriyah.umd.js
Done in 17.74s.
```
After:
```console
$ node scripts/bundle.mjs
writing dist/meriyah.mjs
writing dist/meriyah.min.mjs
writing dist/meriyah.umd.js
writing dist/meriyah.umd.min.js
writing dist/meriyah.cjs
Done in 6.65s.
```
=> build: improve bundle speed

src/errors.ts
Not sure why `description` exists at first place, but if it is the same as `.message` makes it completely useless.
Remove location information so that if user don't need it can use `.description` directly.
Prettier is now removing it
https://github.com/prettier/prettier/blob/88e35f974fecd06d64fba59d4dc94a6b371a0728/src/language-js/parse/meriyah.js#L65-L68
=> feat: remove location information from `ParseError.description`

src/meriyah.ts
`ESTree` should only export in types
Before:
```console
> await import('./dist/meriyah.mjs')
[Module: null prototype] {
ESTree: [Object: null prototype] {},
parse: [Function: parse],
parseModule: [Function: parseModule],
parseScript: [Function: parseScript],
version: '6.0.6'
}
```
After:
```console
> await import('./dist/meriyah.mjs')
[Module: null prototype] {
parse: [Function: parse],
parseModule: [Function: parseModule],
parseScript: [Function: parseScript],
version: '6.0.6'
}
```
=> fix: remove `ESTree` export

src/common.ts, src/errors.ts, src/estree.ts, src/parser.ts
Use `tokenStart` instead of individual `tokenIndex`,`tokenLine`,`tokenColumn` which can easily get wrong, I see a few places already not correct.
=> refactor: add `tokenStart` getter to `Parser`

src/parser.ts, src/parser/parser.ts
Replace `context` with props.
I also move `start` to sencode parameter, since I plan to add optional `end` parameter, and in future, maybe we can make `start` optional too.
=> refactor: update signature of `Parser#finishNode()`

src/common.ts, src/errors.ts, src/estree.ts, src/lexer/comments.ts, src/lexer/common.ts, src/lexer/identifier.ts, src/lexer/jsx.ts, src/lexer/numeric.ts, src/lexer/regexp.ts, src/lexer/scan.ts, src/lexer/string.ts, src/lexer/template.ts, src/parser.ts, src/parser/parser.ts, test/lexer/comments.ts, test/lexer/identifiers.ts, test/lexer/line-terminators.ts, test/lexer/numbers.ts, test/lexer/privatename.ts, test/lexer/punctuators.ts, test/lexer/regexp.ts, test/lexer/scanSingleToken.ts, test/lexer/skiphashbang.ts, test/lexer/strings.ts, test/lexer/template.ts, test/lexer/unicode-escape.ts, test/lexer/whitespace.ts
- Pack various options into an object
- Reuse in `pushComment` and `pushToken`
- Stricter type in `OnComment`
=> refactor: refine `Parser`

src/lexer/string.ts, test/parser/expressions/__snapshots__/string.ts.snap, test/parser/expressions/string.ts
Turns out [#477](https://github.com/meriyah/meriyah/pull/477) is not corret, it should not count a new line when escaped...
=> fix(parser): fix line/column where string literal contains `U+2028` or `U+2029` followed by `\`

src/estree.ts
=> chore: remove unused `Import` node

eslint.config.mjs, scripts/internal-eslint-plugin.mjs, src/parser.ts
Without it
After type parameters added
=> chore: enforce type parameter for `parser.finishNode()`

src/parser.ts, src/parser/parser.ts, src/parser/scope.ts
So we don't need pass `parser` around.
=> refactor: add `Parser#{createScope,createScopeIfLexical}()`

src/parser/private-scope.ts
Similar to #502, save identifiers in a Map instead of `PrivateScope` itself.
=> refactor: improve private identifier tracking

src/common.ts, src/parser.ts, src/parser/parser.ts, src/parser/scope.ts, test/parser/module/__snapshots__/export.ts.snap, test/parser/module/export.ts
- Change `exportedNames` to a `Set`
- Add `Parser#declareUnboundVariable()`
- Fix duplicate export as empty string, and add tests https://github.com/meriyah/meriyah/pull/502#discussion_r2176807681
=> refactor: move `declareUnboundVariable` to `Parser`

src/parser.ts, src/parser/parser.ts, test/parser/miscellaneous/unique-node.ts
I'll fix the shorthand import/export specifiers soon.
=> fix(parser): generate unique location info for shorthand pattern

eslint.config.mjs, package.json, test/lexer/numbers.ts
[unicorn/prefer-bigint-literals](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/prefer-bigint-literals.md)
This is actually how I came up with the idea for this rule.
=> chore: enable `unicorn/prefer-bigint-literals` rule
